name: Frontend_MoviGO
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias actualizadas a versiones compatibles
  http: ^1.1.0
  supabase_flutter: ^2.6.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  dio: ^5.4.0
  jwt_decoder: ^2.0.1
  intl: ^0.19.0
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.2.2
  connectivity_plus: ^6.0.3

  # Dependencias de mapa actualizadas
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true